name: drand-ea
description: An external adapter to get randomness from drand.love
node_identifier: hicetnunc2000
platforms:
  - AWS Lambda
data_sources:
  - name: drand-ea
    url: https://zw4l2zt531.execute-api.us-east-1.amazonaws.com/dev/drand_ea
parameters:
