service: drand-ea
#org: @hicetnunc2000

frameworkVersion: '2.8.0'

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x

functions:
  drand_handler:
    handler: handler.drand_handler
    events:
      - http:
          path: drand_handler
          method: post
          cors:
            origin: '*'
